#cloud-config
autoinstall:
  version: 1
  locale: es_AR.UTF-8
  keyboard:
    layout: latam
    variant: deadtilde
  timezone: America/Argentina/Buenos_Aires

  identity:
    hostname: k8s-node
    username: ubuntu
    password: "$6$btReBFXrjlfTZbQ4$ZmYNs6XhfTRRVCX0u7wNb2Tndh64YbKFS3APgrqi99FrJsLNlL5BNAkgiIM3cDEydrN1pWKgwShIqu0THavba/" #ubuntu

  ssh:
    install-server: true
    allow-pw: true

  storage:
    layout:
      name: lvm

  packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - containerd
    - iotop
    - htop
    - tcpdump
    - hping3
    - nmap
    - bmon
    - btop
    - mc
    - dnsutils
    - net-tools
    - fail2ban
    - bridge-utils
    - jq
    - vim
    - rsync
    - ntp
    - ntpdate
    - sshpass

  late-commands:
    - curtin in-target --target=/target swapoff -a
    - curtin in-target --target=/target sed -i.bak '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
    - curtin in-target --target=/target mkdir -p /etc/containerd
    - curtin in-target --target=/target bash -c "containerd config default > /etc/containerd/config.toml"
    - curtin in-target --target=/target sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
    - curtin in-target --target=/target systemctl enable containerd
    - curtin in-target --target=/target curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    - curtin in-target --target=/target bash -c "echo 'deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' > /etc/apt/sources.list.d/kubernetes.list"
    - curtin in-target --target=/target apt-get update
    - curtin in-target --target=/target apt-get install -y kubelet kubeadm kubectl
    - curtin in-target --target=/target apt-mark hold kubelet kubeadm kubectl
    - curtin in-target --target=/target bash -c "echo 'net.bridge.bridge-nf-call-iptables=1' > /etc/sysctl.d/k8s.conf"
    - curtin in-target --target=/target bash -c "echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.d/k8s.conf"
    - curtin in-target --target=/target sysctl --system
    - curtin in-target --target=/target timedatectl set-timezone America/Argentina/Buenos_Aires
