#cloud-config
autoinstall:
  version: 1
  locale: en_US.UTF-8
  keyboard:
    layout: us
    variant: ''
  network:
    version: 2
    ethernets:
      ens160:  # depende de cómo Hyper-V nombre la interfaz
        dhcp4: true
  identity:
    hostname: k8s-node
    username: ubuntu
    password: "$6$rounds=4096$SOMEHASH..."  # hash SHA-512 generado con mkpasswd
  ssh:
    install-server: true
    authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQ...
  storage:
    layout:
      name: lvm
  packages:
    - containerd
    - curl
    - vim
    - htop
    - net-tools
    - dnsutils
    - jq
    - mc
    - rsync
    - fail2ban
    - ntp
    - ntpdate
    - bmon
    - btop
    - tcpdump
    - nmap
    - bridge-utils
    - iotop
  late-commands:
    - curtin in-target --target=/target swapoff -a
    - curtin in-target --target=/target sed -i.bak '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
    - curtin in-target --target=/target mkdir -p /etc/containerd
    - curtin in-target --target=/target bash -c "containerd config default > /etc/containerd/config.toml"
    - curtin in-target --target=/target sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
    - curtin in-target --target=/target systemctl enable containerd
    - curtin in-target --target=/target curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    - curtin in-target --target=/target bash -c "echo 'deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' > /etc/apt/sources.list.d/kubernetes.list"
    - curtin in-target --target=/target apt-get update
    - curtin in-target --target=/target apt-get install -y kubelet kubeadm kubectl
    - curtin in-target --target=/target apt-mark hold kubelet kubeadm kubectl
    - curtin in-target --target=/target bash -c "echo 'net.bridge.bridge-nf-call-iptables=1' > /etc/sysctl.d/k8s.conf"
    - curtin in-target --target=/target bash -c "echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.d/k8s.conf"
    - curtin in-target --target=/target sysctl --system
    - curtin in-target --target=/target timedatectl set-timezone America/Argentina/Buenos_Aires
